apiVersion: v1
kind: Service
metadata:
  name: {{ quote .Values.name }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: {{ quote .Values.name }}
