apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: https
      port: {{ .Values.webhookServicePort }}
      targetPort: 443
    - name: health
      port: {{ .Values.healthServicePort }}
      targetPort: 80
  selector:
    service: {{ .Chart.Name }}
